apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: django
  labels:
    app: django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-container
          image: django-app:v1
          ports:
            - containerPort: 8000
          env:
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DJANGO_ALLOWED_HOSTS
      restartPolicy: Always